[package]
name = "jsonpath-rust"
version = "0.1.0"
authors = ["BorisZhguchev <zhguchev@gmail.com>"]
edition = "2018"

[dependencies]
serde_json = "1.0"
regex = "1"
pest = "2.0"
pest_derive = "2.0"

[dev-dependencies]
lazy_static = "1.0"